In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [3]:
df = pd.read_csv('lungcancer.csv')
df2 = pd.read_csv('drug_deaths.csv')

In [23]:
df.isna().sum()

index                       0
Patient Id                  0
Age                         0
Gender                      0
Air Pollution               0
Alcohol use                 0
Dust Allergy                0
OccuPational Hazards        0
Genetic Risk                0
chronic Lung Disease        0
Balanced Diet               0
Obesity                     0
Smoking                     0
Passive Smoker              0
Chest Pain                  0
Coughing of Blood           0
Fatigue                     0
Weight Loss                 0
Shortness of Breath         0
Wheezing                    0
Swallowing Difficulty       0
Clubbing of Finger Nails    0
Frequent Cold               0
Dry Cough                   0
Snoring                     0
Level                       0
dtype: int64

In [24]:
df.columns

Index(['index', 'Patient Id', 'Age', 'Gender', 'Air Pollution', 'Alcohol use',
       'Dust Allergy', 'OccuPational Hazards', 'Genetic Risk',
       'chronic Lung Disease', 'Balanced Diet', 'Obesity', 'Smoking',
       'Passive Smoker', 'Chest Pain', 'Coughing of Blood', 'Fatigue',
       'Weight Loss', 'Shortness of Breath', 'Wheezing',
       'Swallowing Difficulty', 'Clubbing of Finger Nails', 'Frequent Cold',
       'Dry Cough', 'Snoring', 'Level'],
      dtype='object')

In [25]:
df["Level"].value_counts()

Level
High      365
Medium    332
Low       303
Name: count, dtype: int64

In [26]:
df=df.drop(['index','Patient Id'],axis=1)

In [27]:
#sns.pairplot(df)

In [28]:
df=df.replace('Low',0)
df=df.replace('Medium',1)
df=df.replace('High',2)

/var/folders/cm/r8plqqp5119b00wn4rf53dpc0000gn/T/ipykernel_7704/2686353387.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df=df.replace('High',2)

In [29]:
df['Level'].value_counts()

Level
2    365
1    332
0    303
Name: count, dtype: int64

In [30]:
cl = df.corr()

In [31]:
cl=cl.sort_values(by="Level",ascending=False)

In [32]:
varN = ['Obesity','Coughing of Blood',
'Alcohol use',
'Dust Allergy',
'Balanced Diet',
'Passive Smoker',
'Genetic Risk',
'OccuPational Hazards',
'Chest Pain',
'Air Pollution',
'Fatigue',
'chronic Lung Disease',
'Smoking',
'Shortness of Breath',
'Frequent Cold','Level']

In [33]:
finaldf=df[varN]

In [34]:
finaldf.head()

,Obesity,Coughing of Blood,Alcohol use,Dust Allergy,Balanced Diet,Passive Smoker,Genetic Risk,OccuPational Hazards,Chest Pain,Air Pollution,Fatigue,chronic Lung Disease,Smoking,Shortness of Breath,Frequent Cold,Level
0,4,4,4,5,2,2,3,4,2,2,3,2,3,2,2,0
1,2,3,1,5,2,4,4,3,2,3,1,2,2,7,1,1
2,7,8,5,6,6,3,5,5,4,4,8,4,2,9,6,2
3,7,8,7,7,7,7,6,7,7,7,4,7,7,3,6,2
4,7,9,8,7,7,7,7,7,7,6,3,6,8,4,4,2

In [35]:
finaldf.describe()

,Obesity,Coughing of Blood,Alcohol use,Dust Allergy,Balanced Diet,Passive Smoker,Genetic Risk,OccuPational Hazards,Chest Pain,Air Pollution,Fatigue,chronic Lung Disease,Smoking,Shortness of Breath,Frequent Cold,Level
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,4.465000,4.859000,4.563000,5.165000,4.491000,4.195000,4.580000,4.840000,4.438000,3.8400,3.856000,4.380000,3.948000,4.240000,3.536000,1.062000
std,2.124921,2.427965,2.620477,1.980833,2.135528,2.311778,2.126999,2.107805,2.280209,2.0304,2.244616,1.848518,2.495902,2.285087,1.832502,0.815365
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,3.000000,3.000000,2.000000,4.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.0000,2.000000,3.000000,2.000000,2.000000,2.000000,0.000000
50%,4.000000,4.000000,5.000000,6.000000,4.000000,4.000000,5.000000,5.000000,4.000000,3.0000,3.000000,4.000000,3.000000,4.000000,3.000000,1.000000
75%,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,6.0000,5.000000,6.000000,7.000000,6.000000,5.000000,2.000000
max,7.000000,9.000000,8.000000,8.000000,7.000000,8.000000,7.000000,8.000000,9.000000,8.0000,9.000000,7.000000,8.000000,9.000000,7.000000,2.000000

In [ ]:
sns.pairplot(finaldf)

In [39]:
x= finaldf.drop("Level", axis=1).values
y= finaldf['Level'].values

In [43]:
type(y)

numpy.ndarray

# Splittling dataset into train and test

In [56]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest= train_test_split(x,y,test_size=0.2,random_state=1)

In [57]:
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(800, 15)
(200, 15)
(800,)
(200,)

# Feature Scaling

In [58]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
xtrain=sc.fit_transform(xtrain)

In [59]:
xtrain

array([[-1.17088533, -1.57782516, -0.98770594, ..., -0.37105903,
        -0.56021873,  0.78882614],
       [ 1.18620643,  0.88432074,  0.92367469, ...,  1.23352056,
         1.18365281,  1.87874136],
       [ 1.18620643,  0.88432074,  0.92367469, ...,  1.23352056,
         0.74768492, -0.84604669],
       ...,
       [-0.69946698,  0.47396309,  1.30595082, ...,  1.63466545,
         0.31171704, -1.3910043 ],
       [-0.22804863, -1.16746751, -0.98770594, ...,  0.83237566,
         1.18365281, -0.84604669],
       [-1.17088533,  1.29467838,  0.92367469, ...,  0.03008587,
         0.74768492, -1.3910043 ]])

# Random Forest Classification

In [60]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10,criterion="entropy",random_state=0)
classifier.fit(xtrain,ytrain)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [61]:
predictions=classifier.predict(sc.fit_transform(xtest))
print(predictions)
print(ytest)

[1 0 1 0 2 0 0 0 2 0 0 2 1 1 1 2 2 0 0 0 0 2 0 0 2 1 2 2 0 0 2 0 1 0 1 0 1
 0 2 0 2 1 1 1 2 2 2 0 1 2 0 0 1 1 0 2 2 2 0 1 1 1 0 2 0 2 2 0 1 2 0 0 1 1
 0 1 1 0 2 1 0 1 2 2 1 2 1 1 2 1 2 1 1 2 1 2 2 0 0 0 0 2 2 0 2 0 0 2 0 0 1
 1 0 0 2 1 0 2 1 2 1 2 2 1 2 2 2 1 1 1 2 1 2 2 2 1 2 1 1 2 1 0 0 2 2 1 1 2
 2 2 2 1 1 1 0 2 0 2 1 0 0 2 0 2 2 1 2 0 2 1 2 1 0 2 2 0 1 1 0 2 2 0 0 0 2
 2 2 1 1 1 0 0 2 1 1 2 2 2 0 2]
[1 0 1 0 2 0 0 0 2 0 0 2 1 1 1 2 2 0 0 0 0 2 0 0 2 1 2 2 0 0 2 0 1 0 1 0 1
 0 2 0 2 1 1 1 2 2 2 0 1 2 0 0 1 1 0 2 2 2 0 1 1 1 0 2 0 2 2 0 1 2 0 0 1 1
 0 1 1 0 2 1 0 1 2 2 1 2 1 1 2 1 2 1 1 2 1 2 2 0 0 0 0 2 2 0 2 0 0 2 0 0 1
 1 0 0 2 1 0 2 1 2 1 2 2 1 2 2 2 1 1 1 2 1 2 2 2 1 2 1 1 2 1 0 0 2 2 1 1 2
 2 2 2 1 1 1 0 2 0 2 1 0 0 2 0 2 2 1 2 0 2 1 2 1 0 2 2 0 1 1 0 2 2 0 0 0 2
 2 2 1 1 1 0 0 2 1 1 2 2 2 0 2]

In [62]:
from sklearn import metrics
metrics.confusion_matrix(ytest,predictions)

array([[62,  0,  0],
       [ 0, 62,  0],
       [ 0,  0, 76]])

In [63]:
metrics.accuracy_score(ytest,predictions)

1.0

In [65]:
metrics.recall_score(ytest,predictions,average="weighted")

1.0

# Logistic Regression

In [66]:
from sklearn.linear_model import LogisticRegression
lclassifier=LogisticRegression(random_state=0)
lclassifier.fit(xtrain,ytrain)

LogisticRegression(random_state=0)

In [67]:
predictions=lclassifier.predict(sc.fit_transform(xtest))
print(predictions)
print(ytest)

[1 0 1 0 2 0 0 0 2 0 0 2 1 1 1 2 2 0 0 0 0 2 0 0 2 1 2 2 0 0 2 0 1 0 1 0 1
 0 2 0 2 1 1 1 2 2 2 0 1 2 0 0 1 1 0 2 2 2 0 1 1 1 0 2 0 2 2 1 1 2 0 0 1 1
 0 1 1 0 2 1 0 1 2 2 1 2 1 1 2 1 2 1 1 2 1 2 2 0 0 0 0 2 2 0 2 0 0 2 0 0 1
 1 0 0 2 1 0 2 1 2 1 2 2 1 2 2 2 1 1 1 2 1 2 2 2 1 2 1 1 2 1 0 0 2 2 1 1 2
 2 2 2 1 1 1 0 2 1 2 1 0 0 2 0 2 2 1 2 0 2 1 2 1 0 2 2 0 1 1 0 2 2 0 0 0 2
 2 2 1 1 1 0 0 2 1 1 2 2 2 0 2]
[1 0 1 0 2 0 0 0 2 0 0 2 1 1 1 2 2 0 0 0 0 2 0 0 2 1 2 2 0 0 2 0 1 0 1 0 1
 0 2 0 2 1 1 1 2 2 2 0 1 2 0 0 1 1 0 2 2 2 0 1 1 1 0 2 0 2 2 0 1 2 0 0 1 1
 0 1 1 0 2 1 0 1 2 2 1 2 1 1 2 1 2 1 1 2 1 2 2 0 0 0 0 2 2 0 2 0 0 2 0 0 1
 1 0 0 2 1 0 2 1 2 1 2 2 1 2 2 2 1 1 1 2 1 2 2 2 1 2 1 1 2 1 0 0 2 2 1 1 2
 2 2 2 1 1 1 0 2 0 2 1 0 0 2 0 2 2 1 2 0 2 1 2 1 0 2 2 0 1 1 0 2 2 0 0 0 2
 2 2 1 1 1 0 0 2 1 1 2 2 2 0 2]

In [68]:
from sklearn import metrics
metrics.confusion_matrix(ytest,predictions)

array([[60,  2,  0],
       [ 0, 62,  0],
       [ 0,  0, 76]])

In [69]:
metrics.accuracy_score(ytest,predictions)

0.99

# Decisive Tree

In [71]:
from sklearn.tree import DecisionTreeClassifier
dclassifier = DecisionTreeClassifier(criterion="entropy",random_state=0)
dclassifier.fit(xtrain,ytrain)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [72]:
predictions=dclassifier.predict(sc.fit_transform(xtest))
print(predictions)
print(ytest)

[1 0 1 0 2 0 0 0 2 0 0 2 1 1 1 2 2 0 0 0 0 2 0 0 2 1 2 2 0 0 2 0 1 0 1 0 1
 0 2 0 2 1 1 1 2 2 2 0 1 2 0 0 1 1 0 2 2 2 0 1 1 1 0 2 0 2 2 0 1 2 0 0 1 1
 0 1 1 0 2 1 0 1 2 2 1 2 1 1 2 1 2 1 1 2 1 2 2 0 0 0 0 2 2 0 2 0 0 2 0 0 1
 1 0 0 2 1 0 2 1 2 1 2 2 1 2 2 2 1 1 1 2 1 2 2 2 1 2 1 1 2 1 0 0 2 2 1 1 2
 2 2 2 1 1 1 0 2 0 2 1 0 0 2 0 2 2 1 2 0 2 1 2 1 0 2 2 0 1 1 0 2 2 0 0 0 2
 2 2 1 1 1 0 0 2 1 1 2 2 2 0 2]
[1 0 1 0 2 0 0 0 2 0 0 2 1 1 1 2 2 0 0 0 0 2 0 0 2 1 2 2 0 0 2 0 1 0 1 0 1
 0 2 0 2 1 1 1 2 2 2 0 1 2 0 0 1 1 0 2 2 2 0 1 1 1 0 2 0 2 2 0 1 2 0 0 1 1
 0 1 1 0 2 1 0 1 2 2 1 2 1 1 2 1 2 1 1 2 1 2 2 0 0 0 0 2 2 0 2 0 0 2 0 0 1
 1 0 0 2 1 0 2 1 2 1 2 2 1 2 2 2 1 1 1 2 1 2 2 2 1 2 1 1 2 1 0 0 2 2 1 1 2
 2 2 2 1 1 1 0 2 0 2 1 0 0 2 0 2 2 1 2 0 2 1 2 1 0 2 2 0 1 1 0 2 2 0 0 0 2
 2 2 1 1 1 0 0 2 1 1 2 2 2 0 2]

In [73]:
from sklearn import metrics
metrics.confusion_matrix(ytest,predictions)

array([[62,  0,  0],
       [ 0, 62,  0],
       [ 0,  0, 76]])